### ISSUE TITLE
Feature request: optional parameters to pass to `parse_obj`

### ISSUE THREAD

**Issue by bjones1** [dapper91/pydantic-xml#82]
For some models, I'd like to be able to store some metadata (for example, the path to the XML file) in the model. I'd like a way to specify this during model creation/validation. Something like:

``` Python
from pathlib import Path
from typing import List
from pydantic_xml import BaseXmlModel, element


class Company(BaseXmlModel, tag="Company"):
    xml_path: Path
    website: List[str] = element()


path = Path("test.xml")
################### See extra xml_path argument here.
company = Company.from_xml(path.read_bytes(), xml_path=path)
print(company)
```

**Comment by dapper91** [comment]
@bjones1 Hi

Maybe I am wrong, but it seems to me that since ``xml_path`` contains meta-information it should not be a part of the model fields. In your example ``xml_path`` is bound to the element text which is not right I suppose.

For that purposes pydantic supports [private attributes](https://docs.pydantic.dev/latest/usage/models/#private-model-attributes):

```python
class Company(BaseXmlModel, tag="Company"):
    _xml_path: Path = PrivateAttr()
    website: List[str] = element()
```

Also pydantic supports [validation context](https://docs.pydantic.dev/latest/usage/validators/#validation-context) which allows you to pass some meta-data to the validators.

So it seems to me that your problem could be solved without extra arguments, like this:

```python
from pathlib import Path
from typing import List, Self
from pydantic import model_validator, PrivateAttr, ValidationInfo
from pydantic_xml import BaseXmlModel, element


class Company(BaseXmlModel, tag="Company"):
    _xml_path: Path = PrivateAttr()
    website: List[str] = element()

    @model_validator(mode='after')
    def set_metadata(cls, obj: Self, info: ValidationInfo) -> Self:
        obj._xml_path = info.context['xml_path']
        return obj

path = Path("test.xml")
company = Company.from_xml(path.read_bytes(), context=dict(xml_path=path))
print(company)
```

**Comment by bjones1** [comment]
This is very helpful, thanks! I wasn't aware of validation context; this looks like a great way to do what I need. I'd already been storing data using private attributes. Let me play a bit with this and make sure it all works the way I expect.

**Comment by dapper91** [comment]
> I'm assuming I need pydantic-xml 2.2.2?

No, that should work prior to 2.2.2.

**Comment by bjones1** [comment]
OK, thanks!
